"""
========================================================================
PART 6: TIME-FREQUENCY SPECTROGRAM GENERATION (STOCKWELL TRANSFORM)
Project: Automated HFO Detection with ML/DL Architecture

Description:
This script performs Time-Frequency (TF) analysis on the consolidated 1D 
signals. It uses the Stockwell Transform (S-Transform) to convert raw 
voltage traces into 2D spectrograms, optimized for 2D-CNN classification.

Key Features:
- S-Transform: Frequency-dependent resolution (80Hz - 500Hz range).
- Resampling: Normalizes spectral height to 128 pixels using Librosa.
- Memory Management: Patient-wise chunking to prevent RAM overflow.
- Persistence: Fragmented saving allows recovery from interrupted sessions.
========================================================================
"""

import numpy as np
import pandas as pd
import os, gc, shutil
from tqdm.auto import tqdm

# --- Dependency Management ---
try:
    from stockwell import st as st_transform
except ImportError:
    print("[INFO] Installing Stockwell dependency...")
    os.system('pip install -q stockwell')
    from stockwell import st as st_transform

try:
    import librosa
    from joblib import Parallel, delayed
except ImportError:
    print("[INFO] Installing Librosa and Joblib...")
    os.system('pip install -q librosa joblib')
    import librosa
    from joblib import Parallel, delayed

# ==========================================
# 1. DIRECTORY & PATH CONFIGURATION
# ==========================================
script_dir = os.path.dirname(os.path.abspath(__file__))
project_root = os.path.abspath(os.path.join(script_dir, "..", ".."))

# --- INPUT PATH ---
# Master dataset generated by the Consolidator script
INPUT_PATH = os.path.join(project_root, "data", "master", "CONSOLIDATE_CNN_DATASET_200ms_OVERSAMPLED25.parquet")

# --- OUTPUT PATH ---
# Results stored in processed/SPECTRO_DATA_STOCKWELL
OUTPUT_BASE = os.path.join(project_root, "data", "processed", "SPECTRO_DATA_STOCKWELL")
os.makedirs(OUTPUT_BASE, exist_ok=True)

# ==========================================
# 2. TRANSFORM ENGINE (STOCKWELL LOGIC)
# ==========================================
def _one_wave_to_st_power(wave):
    """
    Computes Stockwell Transform power and normalizes to uint8 images.
    """
    try:
        # Frequency resolution (df) based on sampling (2000Hz) and length
        df = 2000 / len(wave)
        
        # Transform targeting the HFO band (80Hz to 500Hz)
        s_mat = st_transform.st(wave, int(80/df), int(500/df))
        power = (np.abs(s_mat) ** 2).astype(np.float32)
        
        # Resample frequency axis to 128 for CNN consistency
        power = librosa.resample(power, orig_sr=power.shape[0], target_sr=128, axis=0)
        power = power[:, :400] # Ensure temporal length consistency
        
        # Min-Max Normalization to [0, 255] for uint8 storage efficiency
        p_min, p_max = power.min(), power.max()
        power = (power - p_min) / (p_max - p_min + 1e-8)
        return (power * 255).astype(np.uint8)
    except Exception as e:
        return np.zeros((128, 400), dtype=np.uint8)

# ==========================================
# 3. PROCESSING LOOP WITH CHECKPOINTING
# ==========================================
if not os.path.exists(INPUT_PATH):
    raise FileNotFoundError(f"[ERROR] Master dataset not found at: {INPUT_PATH}")
else:
    print(f"[INFO] Loading master dataset for TF conversion...")
    df_full = pd.read_parquet(INPUT_PATH, columns=["Patient", "Raw_Voltage", "Multiclass_Label"])
    patients = sorted(df_full["Patient"].unique())

    for pat_id in patients:
        # Directory for patient-specific spectral fragments
        pat_folder = os.path.join(OUTPUT_BASE, f"Pat_{pat_id}_Fragments")
        final_file_x = os.path.join(OUTPUT_BASE, f"Pat_{pat_id}_X.npy")

        # Skip if patient processing is already completed
        if os.path.exists(final_file_x):
            print(f"[SKIP] Patient {pat_id} already exists. Skipping...")
            continue

        os.makedirs(pat_folder, exist_ok=True)

        # Filter data for current patient
        pat_df = df_full[df_full["Patient"] == pat_id].copy()
        X_raw = np.stack(pat_df["Raw_Voltage"].values)
        y_raw = pat_df["Multiclass_Label"].values.astype(np.uint8)

        n_samples = len(X_raw)
        CHUNK_SIZE = 250 # Batch size for iterative disk writing

        print(f"\n[EXECUTION] Processing Patient {pat_id} ({n_samples} samples)...")

        for i in range(0, n_samples, CHUNK_SIZE):
            chunk_file = os.path.join(pat_folder, f"chunk_{i}.npy")

            # Checkpoint: Skip existing chunks if session was interrupted
            if os.path.exists(chunk_file):
                continue

            batch_raw = X_raw[i : i + CHUNK_SIZE]

            # Parallel processing (2 jobs for RAM stability in Colab/Cloud)
            batch_res = Parallel(n_jobs=2)(delayed(_one_wave_to_st_power)(w) for w in batch_raw)

            # Consolidate batch and save as numpy array
            chunk_data = np.stack(batch_res, axis=0)[..., None]
            np.save(chunk_file, chunk_data)

            print(f"[PROGRESS] Saved chunk {i}/{n_samples} for Patient {pat_id}")

            del batch_raw, batch_res, chunk_data
            gc.collect()

        print(f"[SUCCESS] Patient {pat_id} fragmentation complete.")

    print("\n[INFO] ALL TIME-FREQUENCY FRAGMENTS EXPORTED SUCCESSFULLY.")
