"""
========================================================================
  PART 2: XGBOOST HFO SCREENER & FEATURE INTERPRETABILITY
  Project: Automated HFO Detection with ML/DL Architecture
  
  Description:
  This script implements an Extreme Gradient Boosting (XGBoost) classifier 
  acting as a high-sensitivity 'Screener' for HFO candidates. It uses 
  Leave-One-Patient-Out (LOPO) cross-validation to ensure patient-independent 
  generalization and utilizes SHAP (SHapley Additive exPlanations) for 
  post-hoc clinical validation of spectral and temporal biomarkers.

  Key Features:
  - Validation Strategy: Leave-One-Group-Out (LOGO/LOPO) by Patient.
  - Imbalance Handling: Dynamic 'scale_pos_weight' calculation per fold.
  - Interpretability: SHAP values for global and local feature importance.
  - Pipeline Role: Binary filter (Threshold: 0.30) to reduce false positives 
    before Deep Learning classification.
=========================================================================
"""

import pandas as pd
import numpy as np
import xgboost as xgb
import os
import shap
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import LeaveOneGroupOut
from sklearn.metrics import (
    confusion_matrix, f1_score, accuracy_score, recall_score,
    precision_score, roc_auc_score, average_precision_score
)

# ==========================================
# 1. CONFIGURATION & DIRECTORY SETUP
# ==========================================
# Get the absolute path of the current script (src/python/)
script_dir = os.path.dirname(os.path.abspath(__file__))

# Navigate to the project root (HFO-Hybrid-Detection/)
project_root = os.path.abspath(os.path.join(script_dir, "..", ".."))

# 1. Inbound: Master dataset generated by MATLAB merger
INPUT_PATH = os.path.join(project_root, "data", "master", "HFO_MASTER_DATASET_200ms.parquet")

# 2. Outbound: Results directory for XGBoost metrics and model
OUTPUT_DIR = os.path.join(project_root, "data", "processed", "XGBOOST_SCREENER_RESULTS")

# 3. Deep Learning Interface: Parquet list for the CNN classifier
OUTPUT_FILE_CNN = os.path.join(OUTPUT_DIR, "CNN_INPUT_LIST_200ms.parquet")

# Ensure output directory exists
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)
    print(f"[INFO] Created output directory: {OUTPUT_DIR}")

print(f"[INFO] Project Root detected at: {project_root}")

# Sensitivity threshold for the screening phase (Prioritizing Recall)
GATEKEEPER_THRESHOLD = 0.30

# XGBoost Hyperparameters optimized for GPU histogram-based training
XGB_PARAMS = {
    "n_estimators": 1000,
    "learning_rate": 0.03,
    "max_depth": 5,
    "subsample": 0.7,
    "colsample_bytree": 0.8,
    "eval_metric": 'aucpr',
    "early_stopping_rounds": 100,
    "n_jobs": -1,
    "random_state": 42,
    "tree_method": "hist",
    "device": "cuda" 
}

# Features to be excluded from the training process
DROP_COLS = [
    'Patient', 'Night', 'Interval', 'Filename', 'TimeSec', 'Channel',
    'BipolarChannel', 'BipolarLabel',
    'yR', 'yFR', 'yFRandR', 'yAnyHFO',
    'Target_Binary', 'Target_Multiclass', 'SourceFile'
]

# ==========================================
# 2. EVALUATION METRICS UTILITY
# ==========================================
def calculate_metrics(y_true, y_prob, threshold=0.30):
    """
    Computes standard classification metrics at a specified decision threshold.
    Focuses on Sensitivity and Specificity for clinical screening evaluation.
    """
    y_pred = (y_prob >= threshold).astype(int)
    cm = confusion_matrix(y_true, y_pred, labels=[0, 1])
    
    # Extract confusion matrix components safely
    if cm.size == 4:
        tn, fp, fn, tp = cm.ravel()
    else:
        tn = fp = fn = tp = 0

    return {
        "Accuracy": accuracy_score(y_true, y_pred),
        "F1_Score": f1_score(y_true, y_pred, zero_division=0),
        "Sensitivity": tp / (tp + fn) if (tp + fn) > 0 else 0,
        "Specificity": tn / (tn + fp) if (tn + fp) > 0 else 0,
        "Precision": precision_score(y_true, y_pred, zero_division=0),
        "Recall": recall_score(y_true, y_pred, zero_division=0),
        "AUC": roc_auc_score(y_true, y_prob) if len(np.unique(y_true)) > 1 else 0.5,
        "AUPRC": average_precision_score(y_true, y_prob) if len(np.unique(y_true)) > 1 else 0
    }

# ==========================================
# 3. DATA INGESTION
# ==========================================
print(f"[INFO] Loading Dataset: {INPUT_PATH}")
df_raw = pd.read_parquet(INPUT_PATH)

feature_cols = [c for c in df_raw.columns if c not in DROP_COLS]
print(f"[INFO] Feature count: {len(feature_cols)}")

# ==========================================
# 4. LEAVE-ONE-PATIENT-OUT (LOPO) CROSS-VALIDATION
# ==========================================
print("\n" + "="*60)
print("EXECUTION: Leave-One-Group-Out Cross-Validation")
print("="*60)

# Cast to float32 to optimize memory and GPU throughput
X_all = df_raw[feature_cols].fillna(0).astype(np.float32)
y_all = df_raw['yAnyHFO'].astype(int).values
groups = df_raw['Patient'].values

logo = LeaveOneGroupOut()
y_true_all, y_prob_all = [], []
all_results_list = []

for fold, (train_idx, val_idx) in enumerate(logo.split(X_all, y_all, groups=groups)):
    patient_name = df_raw.iloc[val_idx[0]]['Patient']
    print(f"[FOLD {fold+1}] Validating on Patient: {patient_name}")

    X_train, y_train = X_all.iloc[train_idx], y_all[train_idx]
    X_val, y_val = X_all.iloc[val_idx], y_all[val_idx]

    if len(np.unique(y_train)) < 2:
        print(f"[SKIP] Insufficient class variety in training set.")
        continue

    # Compute scale_pos_weight to address class imbalance (Noise vs HFO)
    counts = np.bincount(y_train)
    scale_weight = counts[0] / counts[1] if counts[1] > 0 else 1.0

    model = xgb.XGBClassifier(scale_pos_weight=scale_weight, **XGB_PARAMS)

    # Execute training with validation monitoring
    if len(np.unique(y_val)) < 2:
        model.set_params(early_stopping_rounds=None)
        model.fit(X_train, y_train, verbose=False)
    else:
        model.fit(X_train, y_train, eval_set=[(X_val, y_val)], verbose=False)

    y_prob = model.predict_proba(X_val)[:, 1]

    # Preserve metadata for downstream CNN processing
    df_fold_results = df_raw.iloc[val_idx].copy()
    df_fold_results['Screener_Prob'] = y_prob.astype(np.float32)

    all_results_list.append(df_fold_results)
    y_true_all.extend(y_val)
    y_prob_all.extend(y_prob)

# ==========================================
# 5. CONSOLIDATED RESULTS & EXPORT
# ==========================================
if len(y_true_all) > 0:
    metrics = calculate_metrics(np.array(y_true_all), np.array(y_prob_all), GATEKEEPER_THRESHOLD)

    print("\n" + "="*60)
    print("GLOBAL SCREENER PERFORMANCE REPORT")
    print("="*60)
    for m, val in metrics.items():
        print(f"{m:<15} | {val:.4f}")

    print(f"\n[INFO] Merging results for Deep Learning pipeline...")
    df_final = pd.concat(all_results_list)

    # Enforce boolean types for clinical labels to maintain consistency
    bool_cols = ['yR', 'yFR', 'yFRandR', 'yAnyHFO']
    for col in bool_cols:
        if col in df_final.columns:
            df_final[col] = df_final[col].astype(bool)

    df_final.to_parquet(OUTPUT_FILE_CNN, index=False)
    print(f"[SUCCESS] CNN-ready Parquet saved to: {OUTPUT_FILE_CNN}")

else:
    print("[ERROR] No predictions generated. Process terminated.")

# ==========================================
# 6. SHAP INTERPRETABILITY & POST-HOC ANALYSIS
# ==========================================
print("\n" + "="*60)
print("INTERPRETABILITY ENGINE: SHAP ANALYSIS")
print("="*60)

# 1. Train a final model on all data for global interpretability
print("[INFO] Training final model on full dataset for SHAP analysis...")
counts_final = np.bincount(y_all)
scale_weight_final = counts_final[0] / counts_final[1] if counts_final[1] > 0 else 1.0

final_model = xgb.XGBClassifier(scale_pos_weight=scale_weight_final, **XGB_PARAMS)
final_model.fit(X_all, y_all, verbose=False)

# 2. Save the final model in the processed directory
MODEL_PATH = os.path.join(OUTPUT_DIR, "W_XGBOOST_SCREENER_MODEL_200ms.json")
final_model.save_model(MODEL_PATH)
print(f"[SUCCESS] Final model saved to: {MODEL_PATH}")

# 3. Running SHAP
print("[INFO] Calculating SHAP values (1000 sample background)...")
X_sample = X_all.sample(n=min(1000, len(X_all)), random_state=42)
explainer = shap.TreeExplainer(final_model)
shap_values = explainer.shap_values(X_sample)

# Feature Importance Ranking
shap_importance = np.abs(shap_values).mean(0)
importance_df = pd.DataFrame({
    'Feature': feature_cols,
    'Mean_Abs_SHAP': shap_importance
}).sort_values(by='Mean_Abs_SHAP', ascending=False)

importance_df.to_csv(os.path.join(OUTPUT_DIR, "Numerical_SHAP_Importance.csv"), index=False)
print("\n[TOP 10 BIOMARKERS BY SHAP CONTRIBUTION]")
print(importance_df.head(10))

# ==========================================
# 7. PERFORMANCE VISUALIZATION
# ==========================================
print("[INFO] Visualizing Normalized Confusion Matrix...")
# Usamos y_prob_all que generamos en el LOPO (es más honesto que usar el modelo final)
y_inf_pred = (np.array(y_prob_all) >= GATEKEEPER_THRESHOLD).astype(int)
cm = confusion_matrix(y_true_all, y_inf_pred)
cm_norm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]

plt.figure(figsize=(8, 6))
sns.heatmap(cm_norm, annot=True, fmt='.2%', cmap='Blues',
            xticklabels=['Noise', 'HFO'], yticklabels=['Noise', 'HFO'])
plt.title(f"XGBoost Screener Normalized Confusion Matrix\n(Threshold: {GATEKEEPER_THRESHOLD})")
plt.ylabel('True Clinical Label')
plt.xlabel('Screener Prediction')
plt.savefig(os.path.join(OUTPUT_DIR, "Screener_Confusion_Matrix.png"))
plt.show()
